### PR TITLE
WIP: Expose kubeconfig (staging)

### PR DESCRIPTION
**Pull request by phaer**
Same as https://github.com/kube-hetzner/kube-hetzner/pull/28, just for the staging branch

### CODE REVIEW

**Comment by mnencia** [comment]
@mysticaltech I think this was not supposed to be closed. It happened because the target branch has been deleted.

**Comment by mysticaltech** [comment]
Oh my bad! Sorry folks, just cleaned up the staging branch! Did not mean to close that one!

**Comment by mysticaltech** [comment]
Please @phaer, just rebase on master. Looking forward to it.

**Comment by phaer** [comment]
Yeah no worries, the branch is intact and I've got everything locally anyways.

Feel free to take over if you've got the time, I am running a bit low atm so I could take me a week or two until everything is done and tested

**Comment by mysticaltech** [comment]
No worries @phaer, me too, kind of short on time, just wanted to make sure we have something stable ASAP with MicroOS. Keep up the good work man!

**Pull request closed without merging**
