### PR TITLE
FEAT: Disable traefik & metrics-server

### PR DESCRIPTION
**Pull request by oujonny**
As disscused in #122 this PR introduces the possibility to disable traefik & metrics-server of k3s.
**Important: Traefik is now disabled by default!**

You can enable/disable these two features with those variables:

```
# If you want to use traefik ingress controller with a loadbalancer
# traefik_enabled = true
...
# If you want to enable k8s metric server or not
# metric_server_enabled = false
```

Additional it fixes an deprecated waring by switchting to local_sensitive_file resrouce for kubeconfig.

### CODE REVIEW

**Comment by mysticaltech** [comment]
Well done @oujonny ! That clean code right there. Will just try it once ASAP and merge.

Will also change Traefik to on by default, as it's actually something that most users want and appreciate working out of the box. But definitely having the ability to disable if needed is fantastic! 👍

And thanks also for the metric server disable option. Two birds with one stone, that's awesome! 🙏

**Comment by mnencia** [comment]
The patch needs a `terraform fmt` pass. Good to merge after this change and after setting traefik enabled by default.

**Comment by mnencia** [comment]
The is another change to do: if traefik is disabled, we should return load_balancer_public_ipv4=null

**Review by mnencia — APPROVED** [review]

**Comment by mysticaltech** [comment]
Thanks @oujonny, merging!

**Pull request merged**
