### PR TITLE
Added documentation to use TLS with traefik

### PR DESCRIPTION
**Pull request by Olivierwenger**
Here's  the tested documentation to quickly spin up an nginx pod with TLS, as asked here https://github.com/kube-hetzner/kube-hetzner/pull/37#issuecomment-1037554173

I'm just not sure about the subdomains part, I usually use one certificate per subdomain,

### CODE REVIEW

**Comment by mysticaltech** [comment]
I love the idea of an examples directory. Thanks for that @Olivierwenger!

@phaer and @mnencia, I propose we merge this without further do, what do you say?

**Comment by phaer** [comment]
Looks good to me, I think there's more to be done regarding more structured examples in the future, but it's a good start
One suggestion: I would prefer `examples` instead of `.examples` in this case. Using hidden directories might make sense for the images, but examples should be discoverable so there's no benefit in hiding them on *nix systems in my opionion.

Thanks, @Olivierwenger!

**Comment by TimHeckel** [comment]
@Olivierwenger  - thank you for documenting this!

**Comment by mysticaltech** [comment]
Thanks folks! @Olivierwenger if you can change from . examples to examples it would be great, then we'll merge! 🙏

**Comment by phaer** [comment]
@Olivierwenger Thanks!

**Comment by Olivierwenger** [comment]
@phaer thanks to you for being so quick :)

**Pull request merged**
