### PR TITLE
added cloudflare dns provider support

### PR DESCRIPTION
**Pull request by michaelsstuff**
Hi @mysticaltech ,

not sure if you still want it, but here is an added example integration of cloudflare. 

Cheers
Michael

### CODE REVIEW

**Comment by mysticaltech** [comment]
It's great, thanks @michaelsstuff, appreciate it very much! About the Cloudflare record for the LB, why do you need it on top of external DNS (that configures ingresses automatically), just curious?

**Comment by mysticaltech** [comment]
The reason I have hesitant about that, is that sometimes the IP changes if we update the number of nodes, for instance, it gets "refreshed" by the CCM and sometimes assigned a new IP.

**Comment by michaelsstuff** [comment]
> 

Hmm sorry I cant quite follow. Assume for a moment I know nothing 🙃
The ingress does not have an inherit capability to change public dns records, rigth? I could run [external-dns](https://github.com/kubernetes-sigs/external-dns) which might be more flexible for deployments.

If so then the Cloudflare record for the LB would only be usefull to address your kube with a name... so not too usefull.

**Comment by mysticaltech** [comment]
Basically, what I do, is connect external-dns to cloudflare, then on each ingress definition I create, I add these annotations:
```
    external-dns.alpha.kubernetes.io/hostname: "nameiwant.myrootdomain.dev"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
```

So basically, and that in turn will point to the LB automatically. I never have to create a direct entry for the LB manually. You do not do this?

**Comment by michaelsstuff** [comment]
Jup that makes a lot more sense. Just tried it, works like a charm.
Then lets throw this pr away :-D

Thank you very much for the hints and explanation!
Cheers
Michael

**Pull request closed without merging**
